<?php
    function adres_il(){ ?>
        <option slug="Adana" value="Adana">Adana</option>
        <option slug="Adıyaman" value="Adıyaman">Adıyaman</option>
        <option slug="Afyonkarahisar" value="Afyonkarahisar">Afyonkarahisar</option>
        <option slug="Ağrı" value="Ağrı">Ağrı</option>
        <option slug="Aksaray" value="Aksaray">Aksaray</option>
        <option slug="Amasya" value="Amasya">Amasya</option>
        <option slug="Ankara" value="Ankara">Ankara</option>
        <option slug="Antalya" value="Antalya">Antalya</option>
        <option slug="Ardahan" value="Ardahan">Ardahan</option>
        <option slug="Artvin" value="Artvin">Artvin</option>
        <option slug="Aydın" value="Aydın">Aydın</option>
        <option slug="Balıkesir" value="Balıkesir">Balıkesir</option>
        <option slug="Bartın" value="Bartın">Bartın</option>
        <option slug="Batman" value="Batman">Batman</option>
        <option slug="Bayburt" value="Bayburt">Bayburt</option>
        <option slug="Bilecik" value="Bilecik">Bilecik</option>
        <option slug="Bingöl" value="Bingöl">Bingöl</option>
        <option slug="Bitlis" value="Bitlis">Bitlis</option>
        <option slug="Bolu" value="Bolu">Bolu</option>
        <option slug="Burdur" value="Burdur">Burdur</option>
        <option slug="Bursa" value="Bursa">Bursa</option>
        <option slug="Çanakkale" value="Çanakkale">Çanakkale</option>
        <option slug="Çankırı" value="Çankırı">Çankırı</option>
        <option slug="Çorum" value="Çorum">Çorum</option>
        <option slug="Denizli" value="Denizli">Denizli</option>
        <option slug="Diyarbakır" value="Diyarbakır">Diyarbakır</option>
        <option slug="Düzce" value="Düzce">Düzce</option>
        <option slug="Edirne" value="Edirne">Edirne</option>
        <option slug="Elazığ" value="Elazığ">Elazığ</option>
        <option slug="Erzincan" value="Erzincan">Erzincan</option>
        <option slug="Erzurum" value="Erzurum">Erzurum</option>
        <option slug="Eskişehir" value="Eskişehir">Eskişehir</option>
        <option slug="Gaziantep" value="Gaziantep">Gaziantep</option>
        <option slug="Giresun" value="Giresun">Giresun</option>
        <option slug="Gümüşhane" value="Gümüşhane">Gümüşhane</option>
        <option slug="Hakkâri" value="Hakkâri">Hakkâri</option>
        <option slug="Hatay" value="Hatay">Hatay</option>
        <option slug="Iğdır" value="Iğdır">Iğdır</option>
        <option slug="Isparta" value="Isparta">Isparta</option>
        <option slug="İstanbul" value="İstanbul">İstanbul</option>
        <option slug="İzmir" value="İzmir">İzmir</option>
        <option slug="Kahramanmaraş" value="Kahramanmaraş">Kahramanmaraş</option>
        <option slug="Karabük" value="Karabük">Karabük</option>
        <option slug="Karaman" value="Karaman">Karaman</option>
        <option slug="Kars" value="Kars">Kars</option>
        <option slug="Kastamonu" value="Kastamonu">Kastamonu</option>
        <option slug="Kayseri" value="Kayseri">Kayseri</option>
        <option slug="Kilis" value="Kilis">Kilis</option>
        <option slug="Kırıkkale" value="Kırıkkale">Kırıkkale</option>
        <option slug="Kırklareli" value="Kırklareli">Kırklareli</option>
        <option slug="Kırşehir" value="Kırşehir">Kırşehir</option>
        <option slug="Kocaeli" value="Kocaeli">Kocaeli</option>
        <option slug="Konya" value="Konya">Konya</option>
        <option slug="Kütahya" value="Kütahya">Kütahya</option>
        <option slug="Malatya" value="Malatya">Malatya</option>
        <option slug="Manisa" value="Manisa">Manisa</option>
        <option slug="Mardin" value="Mardin">Mardin</option>
        <option slug="Mersin" value="Mersin">Mersin</option>
        <option slug="Muğla" value="Muğla">Muğla</option>
        <option slug="Muş" value="Muş">Muş</option>
        <option slug="Nevşehir" value="Nevşehir">Nevşehir</option>
        <option slug="Niğde" value="Niğde">Niğde</option>
        <option slug="Ordu" value="Ordu">Ordu</option>
        <option slug="Osmaniye" value="Osmaniye">Osmaniye</option>
        <option slug="Rize" value="Rize">Rize</option>
        <option slug="Sakarya" value="Sakarya">Sakarya</option>
        <option slug="Samsun" value="Samsun">Samsun</option>
        <option slug="Şanlıurfa" value="Şanlıurfa">Şanlıurfa</option>
        <option slug="Siirt" value="Siirt">Siirt</option>
        <option slug="Sinop" value="Sinop">Sinop</option>
        <option slug="Sivas" value="Sivas">Sivas</option>
        <option slug="Şırnak" value="Şırnak">Şırnak</option>
        <option slug="Tekirdağ" value="Tekirdağ">Tekirdağ</option>
        <option slug="Tokat" value="Tokat">Tokat</option>
        <option slug="Trabzon" value="Trabzon">Trabzon</option>
        <option slug="Tunceli" value="Tunceli">Tunceli</option>
        <option slug="Uşak" value="Uşak">Uşak</option>
        <option slug="Van" value="Van">Van</option>
        <option slug="Yalova" value="Yalova">Yalova</option>
        <option slug="Yozgat" value="Yozgat">Yozgat</option>
        <option slug="Zonguldak" value="Zonguldak">Zonguldak</option><?php
    }

    function adres_ilce(){ ?>
        <option il-slug="Adana" value="Aladağ">Aladağ</option>
        <option il-slug="Adana" value="Ceyhan">Ceyhan</option>
        <option il-slug="Adana" value="Çukurova">Çukurova</option>
        <option il-slug="Adana" value="Feke">Feke</option>
        <option il-slug="Adana" value="İmamoğlu">İmamoğlu</option>
        <option il-slug="Adana" value="Karaisalı">Karaisalı</option>
        <option il-slug="Adana" value="Karataş">Karataş</option>
        <option il-slug="Adana" value="Kozan">Kozan</option>
        <option il-slug="Adana" value="Pozantı">Pozantı</option>
        <option il-slug="Adana" value="Saimbeyli">Saimbeyli</option>
        <option il-slug="Adana" value="Sarıçam">Sarıçam</option>
        <option il-slug="Adana" value="Seyhan">Seyhan</option>
        <option il-slug="Adana" value="Tufanbeyli">Tufanbeyli</option>
        <option il-slug="Adana" value="Yumurtalık">Yumurtalık</option>
        <option il-slug="Adana" value="Yüreğir">Yüreğir</option>
        <option il-slug="Adıyaman" value="Adıyaman">Adıyaman</option>
        <option il-slug="Adıyaman" value="Besni">Besni</option>
        <option il-slug="Adıyaman" value="Çelikhan">Çelikhan</option>
        <option il-slug="Adıyaman" value="Gerger">Gerger</option>
        <option il-slug="Adıyaman" value="Gölbaşı">Gölbaşı</option>
        <option il-slug="Adıyaman" value="Kâhta">Kâhta</option>
        <option il-slug="Adıyaman" value="Samsat">Samsat</option>
        <option il-slug="Adıyaman" value="Sincik">Sincik</option>
        <option il-slug="Adıyaman" value="Tut">Tut</option>
        <option il-slug="Afyonkarahisar" value="Afyonkarahisar">Afyonkarahisar</option>
        <option il-slug="Afyonkarahisar" value="Başmakçı">Başmakçı</option>
        <option il-slug="Afyonkarahisar" value="Bayat">Bayat</option>
        <option il-slug="Afyonkarahisar" value="Bolvadin">Bolvadin</option>
        <option il-slug="Afyonkarahisar" value="Çay">Çay</option>
        <option il-slug="Afyonkarahisar" value="Çobanlar">Çobanlar</option>
        <option il-slug="Afyonkarahisar" value="Dazkırı">Dazkırı</option>
        <option il-slug="Afyonkarahisar" value="Dinar">Dinar</option>
        <option il-slug="Afyonkarahisar" value="Emirdağ">Emirdağ</option>
        <option il-slug="Afyonkarahisar" value="Evciler">Evciler</option>
        <option il-slug="Afyonkarahisar" value="Hocalar">Hocalar</option>
        <option il-slug="Afyonkarahisar" value="İhsaniye">İhsaniye</option>
        <option il-slug="Afyonkarahisar" value="İscehisar">İscehisar</option>
        <option il-slug="Afyonkarahisar" value="Kızılören">Kızılören</option>
        <option il-slug="Afyonkarahisar" value="Sandıklı">Sandıklı</option>
        <option il-slug="Afyonkarahisar" value="Sinanpaşa">Sinanpaşa</option>
        <option il-slug="Afyonkarahisar" value="Sultandağı">Sultandağı</option>
        <option il-slug="Afyonkarahisar" value="Şuhut">Şuhut</option>
        <option il-slug="Ağrı" value="Ağrı">Ağrı</option>
        <option il-slug="Ağrı" value="Diyadin">Diyadin</option>
        <option il-slug="Ağrı" value="Doğubayazıt">Doğubayazıt</option>
        <option il-slug="Ağrı" value="Eleşkirt">Eleşkirt</option>
        <option il-slug="Ağrı" value="Hamur">Hamur</option>
        <option il-slug="Ağrı" value="Patnos">Patnos</option>
        <option il-slug="Ağrı" value="Taşlıçay">Taşlıçay</option>
        <option il-slug="Ağrı" value="Tutak">Tutak</option>
        <option il-slug="Aksaray" value="Aksaray">Aksaray
        <option il-slug="Aksaray" value="Ağaçören">Ağaçören
        <option il-slug="Aksaray" value="Eskil">Eskil
        <option il-slug="Aksaray" value="Gülağaç">Gülağaç
        <option il-slug="Aksaray" value="Güzelyurt">Güzelyurt
        <option il-slug="Aksaray" value="Ortaköy">Ortaköy
        <option il-slug="Aksaray" value="Sarıyahşi">Sarıyahşi
        <option il-slug="Aksaray" value="Sultanhanı">Sultanhanı
        <option il-slug="Amasya" value="Amasya">Amasya</option>
        <option il-slug="Amasya" value="Göynücek">Göynücek</option>
        <option il-slug="Amasya" value="Gümüşhacıköy">Gümüşhacıköy</option>
        <option il-slug="Amasya" value="Hamamözü">Hamamözü</option>
        <option il-slug="Amasya" value="Merzifon">Merzifon</option>
        <option il-slug="Amasya" value="Suluova">Suluova</option>
        <option il-slug="Amasya" value="Taşova">Taşova</option>
        <option il-slug="Ankara" value="Akyurt">Akyurt</option>
        <option il-slug="Ankara" value="Altındağ">Altındağ</option>
        <option il-slug="Ankara" value="Ayaş">Ayaş</option>
        <option il-slug="Ankara" value="Balâ">Balâ</option>
        <option il-slug="Ankara" value="Beypazarı">Beypazarı</option>
        <option il-slug="Ankara" value="Çamlıdere">Çamlıdere</option>
        <option il-slug="Ankara" value="Çankaya">Çankaya</option>
        <option il-slug="Ankara" value="Çubuk">Çubuk</option>
        <option il-slug="Ankara" value="Elmadağ">Elmadağ</option>
        <option il-slug="Ankara" value="Etimesgut">Etimesgut</option>
        <option il-slug="Ankara" value="Evren">Evren</option>
        <option il-slug="Ankara" value="Gölbaşı">Gölbaşı</option>
        <option il-slug="Ankara" value="Güdül">Güdül</option>
        <option il-slug="Ankara" value="Haymana">Haymana</option>
        <option il-slug="Ankara" value="Kalecik">Kalecik</option>
        <option il-slug="Ankara" value="Kahramankazan">Kahramankazan</option>
        <option il-slug="Ankara" value="Keçiören">Keçiören</option>
        <option il-slug="Ankara" value="Kızılcahamam">Kızılcahamam</option>
        <option il-slug="Ankara" value="Mamak">Mamak</option>
        <option il-slug="Ankara" value="Nallıhan">Nallıhan</option>
        <option il-slug="Ankara" value="Polatlı">Polatlı</option>
        <option il-slug="Ankara" value="Pursaklar">Pursaklar</option>
        <option il-slug="Ankara" value="Sincan">Sincan</option>
        <option il-slug="Ankara" value="Şereflikoçhisar">Şereflikoçhisar</option>
        <option il-slug="Ankara" value="Yenimahalle">Yenimahalle</option>
        <option il-slug="Antalya" value="Akseki">Akseki</option>
        <option il-slug="Antalya" value="Aksu">Aksu</option>
        <option il-slug="Antalya" value="Alanya">Alanya</option>
        <option il-slug="Antalya" value="Demre">Demre</option>
        <option il-slug="Antalya" value="Döşemealtı">Döşemealtı</option>
        <option il-slug="Antalya" value="Elmalı">Elmalı</option>
        <option il-slug="Antalya" value="Finike">Finike</option>
        <option il-slug="Antalya" value="Gazipaşa">Gazipaşa</option>
        <option il-slug="Antalya" value="Gündoğmuş">Gündoğmuş</option>
        <option il-slug="Antalya" value="İbradı">İbradı</option>
        <option il-slug="Antalya" value="Kaş">Kaş</option>
        <option il-slug="Antalya" value="Kemer">Kemer</option>
        <option il-slug="Antalya" value="Kepez">Kepez</option>
        <option il-slug="Antalya" value="Konyaaltı">Konyaaltı</option>
        <option il-slug="Antalya" value="Korkuteli">Korkuteli</option>
        <option il-slug="Antalya" value="Kumluca">Kumluca</option>
        <option il-slug="Antalya" value="Manavgat">Manavgat</option>
        <option il-slug="Antalya" value="Muratpaşa">Muratpaşa</option>
        <option il-slug="Antalya" value="Serik">Serik</option>
        <option il-slug="Ardahan" value="Ardahan">Ardahan</option>
        <option il-slug="Ardahan" value="Çıldır">Çıldır</option>
        <option il-slug="Ardahan" value="Damal">Damal</option>
        <option il-slug="Ardahan" value="Göle">Göle</option>
        <option il-slug="Ardahan" value="Hanak">Hanak</option>
        <option il-slug="Ardahan" value="Posof">Posof</option>
        <option il-slug="Artvin" value="Artvin">Artvin</option>
        <option il-slug="Artvin" value="Ardanuç">Ardanuç</option>
        <option il-slug="Artvin" value="Arhavi">Arhavi</option>
        <option il-slug="Artvin" value="Borçka">Borçka</option>
        <option il-slug="Artvin" value="Hopa">Hopa</option>
        <option il-slug="Artvin" value="Kemalpaşa">Kemalpaşa</option>
        <option il-slug="Artvin" value="Murgul">Murgul</option>
        <option il-slug="Artvin" value="Şavşat">Şavşat</option>
        <option il-slug="Artvin" value="Yusufeli">Yusufeli</option>
        <option il-slug="Aydın" value="Bozdoğan">Bozdoğan</option>
        <option il-slug="Aydın" value="Buharkent">Buharkent</option>
        <option il-slug="Aydın" value="Çine">Çine</option>
        <option il-slug="Aydın" value="Didim">Didim</option>
        <option il-slug="Aydın" value="Efeler">Efeler</option>
        <option il-slug="Aydın" value="Germencik">Germencik</option>
        <option il-slug="Aydın" value="İncirliova">İncirliova</option>
        <option il-slug="Aydın" value="Karacasu">Karacasu</option>
        <option il-slug="Aydın" value="Karpuzlu">Karpuzlu</option>
        <option il-slug="Aydın" value="Koçarlı">Koçarlı</option>
        <option il-slug="Aydın" value="Köşk">Köşk</option>
        <option il-slug="Aydın" value="Kuşadası">Kuşadası</option>
        <option il-slug="Aydın" value="Kuyucak">Kuyucak</option>
        <option il-slug="Aydın" value="Nazilli">Nazilli</option>
        <option il-slug="Aydın" value="Söke">Söke</option>
        <option il-slug="Aydın" value="Sultanhisar">Sultanhisar</option>
        <option il-slug="Aydın" value="Yenipazar">Yenipazar</option>
        <option il-slug="Balıkesir" value="Altıeylül">Altıeylül</option>
        <option il-slug="Balıkesir" value="Ayvalık">Ayvalık</option>
        <option il-slug="Balıkesir" value="Balya">Balya</option>
        <option il-slug="Balıkesir" value="Bandırma">Bandırma</option>
        <option il-slug="Balıkesir" value="Bigadiç">Bigadiç</option>
        <option il-slug="Balıkesir" value="Burhaniye">Burhaniye</option>
        <option il-slug="Balıkesir" value="Dursunbey">Dursunbey</option>
        <option il-slug="Balıkesir" value="Edremit">Edremit</option>
        <option il-slug="Balıkesir" value="Erdek">Erdek</option>
        <option il-slug="Balıkesir" value="Gömeç">Gömeç</option>
        <option il-slug="Balıkesir" value="Gönen">Gönen</option>
        <option il-slug="Balıkesir" value="Havran">Havran</option>
        <option il-slug="Balıkesir" value="İvrindi">İvrindi</option>
        <option il-slug="Balıkesir" value="Karesi">Karesi</option>
        <option il-slug="Balıkesir" value="Kepsut">Kepsut</option>
        <option il-slug="Balıkesir" value="Manyas">Manyas</option>
        <option il-slug="Balıkesir" value="Marmara">Marmara</option>
        <option il-slug="Balıkesir" value="Savaştepe">Savaştepe</option>
        <option il-slug="Balıkesir" value="Sındırgı">Sındırgı</option>
        <option il-slug="Balıkesir" value="Susurluk">Susurluk</option>
        <option il-slug="Bartın" value="Bartın İl Merkezi">Bartın İl Merkezi</option>
        <option il-slug="Bartın" value="Amasra">Amasra</option>
        <option il-slug="Bartın" value="Kurucaşile">Kurucaşile</option>
        <option il-slug="Bartın" value="Ulus">Ulus</option>
        <option il-slug="Batman" value="Batman İl Merkezi">Batman İl Merkezi</option>
        <option il-slug="Batman" value="Beşiri">Beşiri</option>
        <option il-slug="Batman" value="Gercüş">Gercüş</option>
        <option il-slug="Batman" value="Hasankeyf">Hasankeyf</option>
        <option il-slug="Batman" value="Kozluk">Kozluk</option>
        <option il-slug="Batman" value="Sason">Sason</option>
        <option il-slug="Bayburt" value="Bayburt İl Merkezi">Bayburt İl Merkezi</option>
        <option il-slug="Bayburt" value="Aydıntepe">Aydıntepe</option>
        <option il-slug="Bayburt" value="Demirözü">Demirözü</option>
        <option il-slug="Bilecik" value="Bilecik İl Merkezi">Bilecik İl Merkezi</option>
        <option il-slug="Bilecik" value="Bozüyük">Bozüyük</option>
        <option il-slug="Bilecik" value="Gölpazarı">Gölpazarı</option>
        <option il-slug="Bilecik" value="İnhisar">İnhisar</option>
        <option il-slug="Bilecik" value="Osmaneli">Osmaneli</option>
        <option il-slug="Bilecik" value="Pazaryeri">Pazaryeri</option>
        <option il-slug="Bilecik" value="Söğüt">Söğüt</option>
        <option il-slug="Bilecik" value="Yenipazar">Yenipazar</option>
        <option il-slug="Bingöl" value="Bingöl İl Merkezi">Bingöl İl Merkezi</option>
        <option il-slug="Bingöl" value="Adaklı">Adaklı</option>
        <option il-slug="Bingöl" value="Genç">Genç</option>
        <option il-slug="Bingöl" value="Karlıova">Karlıova</option>
        <option il-slug="Bingöl" value="Kiğı">Kiğı</option>
        <option il-slug="Bingöl" value="Solhan">Solhan</option>
        <option il-slug="Bingöl" value="Yayladere">Yayladere</option>
        <option il-slug="Bingöl" value="Yedisu">Yedisu</option>
        <option il-slug="Bingöl" value="Bitlis">Bitlis</option>
        <option il-slug="Bitlis" value="Bitlis İl Merkezi">Bitlis İl Merkezi</option>
        <option il-slug="Bitlis" value="Adilcevaz">Adilcevaz</option>
        <option il-slug="Bitlis" value="Ahlat">Ahlat</option>
        <option il-slug="Bitlis" value="Güroymak">Güroymak</option>
        <option il-slug="Bitlis" value="Hizan">Hizan</option>
        <option il-slug="Bitlis" value="Mutki">Mutki</option>
        <option il-slug="Bitlis" value="Tatvan">Tatvan</option>
        <option il-slug="Bolu" value="Bolu İl Merkezi">Bolu İl Merkezi</option>
        <option il-slug="Bolu" value="Dörtdivan">Dörtdivan</option>
        <option il-slug="Bolu" value="Gerede">Gerede</option>
        <option il-slug="Bolu" value="Göynük">Göynük</option>
        <option il-slug="Bolu" value="Kıbrıscık">Kıbrıscık</option>
        <option il-slug="Bolu" value="Mengen">Mengen</option>
        <option il-slug="Bolu" value="Mudurnu">Mudurnu</option>
        <option il-slug="Bolu" value="Seben">Seben</option>
        <option il-slug="Bolu" value="Yeniçağa">Yeniçağa</option>
        <option il-slug="Burdur" value="Burdur İl Merkezi">Burdur İl Merkezi</option>
        <option il-slug="Burdur" value="Ağlasun">Ağlasun</option>
        <option il-slug="Burdur" value="Altınyayla">Altınyayla</option>
        <option il-slug="Burdur" value="Bucak">Bucak</option>
        <option il-slug="Burdur" value="Çavdır">Çavdır</option>
        <option il-slug="Burdur" value="Çeltikçi">Çeltikçi</option>
        <option il-slug="Burdur" value="Gölhisar">Gölhisar</option>
        <option il-slug="Burdur" value="Karamanlı">Karamanlı</option>
        <option il-slug="Burdur" value="Kemer">Kemer</option>
        <option il-slug="Burdur" value="Tefenni">Tefenni</option>
        <option il-slug="Burdur" value="Yeşilova">Yeşilova</option>
        <option il-slug="Burdur" value="Bursa">Bursa</option>
        <option il-slug="Bursa" value="Büyükorhan">Büyükorhan</option>
        <option il-slug="Bursa" value="Gemlik">Gemlik</option>
        <option il-slug="Bursa" value="Gürsu">Gürsu</option>
        <option il-slug="Bursa" value="Harmancık">Harmancık</option>
        <option il-slug="Bursa" value="İnegöl">İnegöl</option>
        <option il-slug="Bursa" value="İznik">İznik</option>
        <option il-slug="Bursa" value="Karacabey">Karacabey</option>
        <option il-slug="Bursa" value="Keles">Keles</option>
        <option il-slug="Bursa" value="Kestel">Kestel</option>
        <option il-slug="Bursa" value="Mudanya">Mudanya</option>
        <option il-slug="Bursa" value="Mustafakemalpaşa">Mustafakemalpaşa</option>
        <option il-slug="Bursa" value="Nilüfer">Nilüfer</option>
        <option il-slug="Bursa" value="Orhaneli">Orhaneli</option>
        <option il-slug="Bursa" value="Orhangazi">Orhangazi</option>
        <option il-slug="Bursa" value="Osmangazi">Osmangazi</option>
        <option il-slug="Bursa" value="Yenişehir">Yenişehir</option>
        <option il-slug="Bursa" value="Yıldırım">Yıldırım</option>
        <option il-slug="Çanakkale" value="Çanakkale İl Merkezi">Çanakkale İl Merkezi</option>
        <option il-slug="Çanakkale" value="Ayvacık">Ayvacık</option>
        <option il-slug="Çanakkale" value="Bayramiç">Bayramiç</option>
        <option il-slug="Çanakkale" value="Biga">Biga</option>
        <option il-slug="Çanakkale" value="Bozcaada">Bozcaada</option>
        <option il-slug="Çanakkale" value="Çan">Çan</option>
        <option il-slug="Çanakkale" value="Eceabat">Eceabat</option>
        <option il-slug="Çanakkale" value="Ezine">Ezine</option>
        <option il-slug="Çanakkale" value="Gelibolu">Gelibolu</option>
        <option il-slug="Çanakkale" value="Gökçeada">Gökçeada</option>
        <option il-slug="Çanakkale" value="Lapseki">Lapseki</option>
        <option il-slug="Çanakkale" value="Yenice">Yenice</option>
        <option il-slug="Çankırı" value="Çankırı İl Merkezi">Çankırı İl Merkezi</option>
        <option il-slug="Çankırı" value="Atkaracalar">Atkaracalar</option>
        <option il-slug="Çankırı" value="Bayramören">Bayramören</option>
        <option il-slug="Çankırı" value="Çerkeş">Çerkeş</option>
        <option il-slug="Çankırı" value="Eldivan">Eldivan</option>
        <option il-slug="Çankırı" value="Ilgaz">Ilgaz</option>
        <option il-slug="Çankırı" value="Kızılırmak">Kızılırmak</option>
        <option il-slug="Çankırı" value="Korgun">Korgun</option>
        <option il-slug="Çankırı" value="Kurşunlu">Kurşunlu</option>
        <option il-slug="Çankırı" value="Orta">Orta</option>
        <option il-slug="Çankırı" value="Şabanözü">Şabanözü</option>
        <option il-slug="Çankırı" value="Yapraklı">Yapraklı</option>
        <option il-slug="Çorum" value="Çorum İl Merkezi">Çorum İl Merkezi</option>
        <option il-slug="Çorum" value="Alaca">Alaca</option>
        <option il-slug="Çorum" value="Bayat">Bayat</option>
        <option il-slug="Çorum" value="Boğazkale">Boğazkale</option>
        <option il-slug="Çorum" value="Dodurga">Dodurga</option>
        <option il-slug="Çorum" value="İskilip">İskilip</option>
        <option il-slug="Çorum" value="Kargı">Kargı</option>
        <option il-slug="Çorum" value="Laçin">Laçin</option>
        <option il-slug="Çorum" value="Mecitözü">Mecitözü</option>
        <option il-slug="Çorum" value="Oğuzlar">Oğuzlar</option>
        <option il-slug="Çorum" value="Ortaköy">Ortaköy</option>
        <option il-slug="Çorum" value="Osmancık">Osmancık</option>
        <option il-slug="Çorum" value="Sungurlu">Sungurlu</option>
        <option il-slug="Çorum" value="Uğurludağ">Uğurludağ</option>
        <option il-slug="Denizli" value="Acıpayam">Acıpayam</option>
        <option il-slug="Denizli" value="Babadağ">Babadağ</option>
        <option il-slug="Denizli" value="Baklan">Baklan</option>
        <option il-slug="Denizli" value="Bekilli">Bekilli</option>
        <option il-slug="Denizli" value="Beyağaç">Beyağaç</option>
        <option il-slug="Denizli" value="Bozkurt">Bozkurt</option>
        <option il-slug="Denizli" value="Buldan">Buldan</option>
        <option il-slug="Denizli" value="Çal">Çal</option>
        <option il-slug="Denizli" value="Çameli">Çameli</option>
        <option il-slug="Denizli" value="Çardak">Çardak</option>
        <option il-slug="Denizli" value="Çivril">Çivril</option>
        <option il-slug="Denizli" value="Güney">Güney</option>
        <option il-slug="Denizli" value="Honaz">Honaz</option>
        <option il-slug="Denizli" value="Kale">Kale</option>
        <option il-slug="Denizli" value="Merkezefendi">Merkezefendi</option>
        <option il-slug="Denizli" value="Pamukkale">Pamukkale</option>
        <option il-slug="Denizli" value="Sarayköy">Sarayköy</option>
        <option il-slug="Denizli" value="Serinhisar">Serinhisar</option>
        <option il-slug="Denizli" value="Tavas">Tavas</option>
        <option il-slug="Diyarbakır" value="Bağlar">Bağlar</option>
        <option il-slug="Diyarbakır" value="Bismil">Bismil</option>
        <option il-slug="Diyarbakır" value="Çermik">Çermik</option>
        <option il-slug="Diyarbakır" value="Çınar">Çınar</option>
        <option il-slug="Diyarbakır" value="Çüngüş">Çüngüş</option>
        <option il-slug="Diyarbakır" value="Dicle">Dicle</option>
        <option il-slug="Diyarbakır" value="Eğil">Eğil</option>
        <option il-slug="Diyarbakır" value="Ergani">Ergani</option>
        <option il-slug="Diyarbakır" value="Hani">Hani</option>
        <option il-slug="Diyarbakır" value="Hazro">Hazro</option>
        <option il-slug="Diyarbakır" value="Kayapınar">Kayapınar</option>
        <option il-slug="Diyarbakır" value="Kocaköy">Kocaköy</option>
        <option il-slug="Diyarbakır" value="Kulp">Kulp</option>
        <option il-slug="Diyarbakır" value="Lice">Lice</option>
        <option il-slug="Diyarbakır" value="Silvan">Silvan</option>
        <option il-slug="Diyarbakır" value="Sur">Sur</option>
        <option il-slug="Diyarbakır" value="Yenişehir">Yenişehir</option>
        <option il-slug="Düzce" value="Düzce İl Merkezi">Düzce İl Merkezi</option>
        <option il-slug="Düzce" value="Akçakoca">Akçakoca</option>
        <option il-slug="Düzce" value="Cumayeri">Cumayeri</option>
        <option il-slug="Düzce" value="Çilimli">Çilimli</option>
        <option il-slug="Düzce" value="Gölyaka">Gölyaka</option>
        <option il-slug="Düzce" value="Gümüşova">Gümüşova</option>
        <option il-slug="Düzce" value="Kaynaşlı">Kaynaşlı</option>
        <option il-slug="Düzce" value="Yığılca">Yığılca</option>
        <option il-slug="Edirne" value="Edirne İl Merkezi">Edirne İl Merkezi</option>
        <option il-slug="Edirne" value="Enez">Enez</option>
        <option il-slug="Edirne" value="Havsa">Havsa</option>
        <option il-slug="Edirne" value="İpsala">İpsala</option>
        <option il-slug="Edirne" value="Keşan">Keşan</option>
        <option il-slug="Edirne" value="Lalapaşa">Lalapaşa</option>
        <option il-slug="Edirne" value="Meriç">Meriç</option>
        <option il-slug="Edirne" value="Süloğlu">Süloğlu</option>
        <option il-slug="Edirne" value="Uzunköprü">Uzunköprü</option>
        <option il-slug="Elâzığ" value="Elazığ İl Merkezi">Elazığ İl Merkezi</option>
        <option il-slug="Elâzığ" value="Ağın">Ağın</option>
        <option il-slug="Elâzığ" value="Alacakaya">Alacakaya</option>
        <option il-slug="Elâzığ" value="Arıcak">Arıcak</option>
        <option il-slug="Elâzığ" value="Baskil">Baskil</option>
        <option il-slug="Elâzığ" value="Karakoçan">Karakoçan</option>
        <option il-slug="Elâzığ" value="Keban">Keban</option>
        <option il-slug="Elâzığ" value="Kovancılar">Kovancılar</option>
        <option il-slug="Elâzığ" value="Maden">Maden</option>
        <option il-slug="Elâzığ" value="Palu">Palu</option>
        <option il-slug="Elâzığ" value="Sivrice">Sivrice</option>
        <option il-slug="Erzincan" value="Erzincan İl Merkezi">Erzincan İl Merkezi</option>
        <option il-slug="Erzincan" value="Çayırlı">Çayırlı</option>
        <option il-slug="Erzincan" value="İliç">İliç</option>
        <option il-slug="Erzincan" value="Kemah">Kemah</option>
        <option il-slug="Erzincan" value="Kemaliye">Kemaliye</option>
        <option il-slug="Erzincan" value="Otlukbeli">Otlukbeli</option>
        <option il-slug="Erzincan" value="Refahiye">Refahiye</option>
        <option il-slug="Erzincan" value="Tercan">Tercan</option>
        <option il-slug="Erzincan" value="Üzümlü">Üzümlü</option>
        <option il-slug="Erzurum" value="Aşkale">Aşkale</option>
        <option il-slug="Erzurum" value="Aziziye">Aziziye</option>
        <option il-slug="Erzurum" value="Çat">Çat</option>
        <option il-slug="Erzurum" value="Hınıs">Hınıs</option>
        <option il-slug="Erzurum" value="Horasan">Horasan</option>
        <option il-slug="Erzurum" value="İspir">İspir</option>
        <option il-slug="Erzurum" value="Karaçoban">Karaçoban</option>
        <option il-slug="Erzurum" value="Karayazı">Karayazı</option>
        <option il-slug="Erzurum" value="Köprüköy">Köprüköy</option>
        <option il-slug="Erzurum" value="Narman">Narman</option>
        <option il-slug="Erzurum" value="Oltu">Oltu</option>
        <option il-slug="Erzurum" value="Olur">Olur</option>
        <option il-slug="Erzurum" value="Palandöken">Palandöken</option>
        <option il-slug="Erzurum" value="Pasinler">Pasinler</option>
        <option il-slug="Erzurum" value="Pazaryolu">Pazaryolu</option>
        <option il-slug="Erzurum" value="Şenkaya">Şenkaya</option>
        <option il-slug="Erzurum" value="Tekman">Tekman</option>
        <option il-slug="Erzurum" value="Tortum">Tortum</option>
        <option il-slug="Erzurum" value="Uzundere">Uzundere</option>
        <option il-slug="Erzurum" value="Yakutiye">Yakutiye</option>
        <option il-slug="Eskişehir" value="Alpu">Alpu</option>
        <option il-slug="Eskişehir" value="Beylikova">Beylikova</option>
        <option il-slug="Eskişehir" value="Çifteler">Çifteler</option>
        <option il-slug="Eskişehir" value="Günyüzü">Günyüzü</option>
        <option il-slug="Eskişehir" value="Han">Han</option>
        <option il-slug="Eskişehir" value="İnönü">İnönü</option>
        <option il-slug="Eskişehir" value="Mahmudiye">Mahmudiye</option>
        <option il-slug="Eskişehir" value="Mihalgazi">Mihalgazi</option>
        <option il-slug="Eskişehir" value="Mihalıççık">Mihalıççık</option>
        <option il-slug="Eskişehir" value="Odunpazarı">Odunpazarı</option>
        <option il-slug="Eskişehir" value="Sarıcakaya">Sarıcakaya</option>
        <option il-slug="Eskişehir" value="Seyitgazi">Seyitgazi</option>
        <option il-slug="Eskişehir" value="Sivrihisar">Sivrihisar</option>
        <option il-slug="Eskişehir" value="Tepebaşı">Tepebaşı</option>
        <option il-slug="Gaziantep" value="Araban">Araban</option>
        <option il-slug="Gaziantep" value="İslahiye">İslahiye</option>
        <option il-slug="Gaziantep" value="Karkamış">Karkamış</option>
        <option il-slug="Gaziantep" value="Nizip">Nizip</option>
        <option il-slug="Gaziantep" value="Nurdağı">Nurdağı</option>
        <option il-slug="Gaziantep" value="Oğuzeli">Oğuzeli</option>
        <option il-slug="Gaziantep" value="Şahinbey">Şahinbey</option>
        <option il-slug="Gaziantep" value="Şehitkamil">Şehitkamil</option>
        <option il-slug="Gaziantep" value="Yavuzeli">Yavuzeli</option>
        <option il-slug="Giresun" value="Giresun İl Merkezi">Giresun İl Merkezi</option>
        <option il-slug="Giresun" value="Alucra">Alucra</option>
        <option il-slug="Giresun" value="Bulancak">Bulancak</option>
        <option il-slug="Giresun" value="Çamoluk">Çamoluk</option>
        <option il-slug="Giresun" value="Çanakçı">Çanakçı</option>
        <option il-slug="Giresun" value="Dereli">Dereli</option>
        <option il-slug="Giresun" value="Doğankent">Doğankent</option>
        <option il-slug="Giresun" value="Espiye">Espiye</option>
        <option il-slug="Giresun" value="Eynesil">Eynesil</option>
        <option il-slug="Giresun" value="Görele">Görele</option>
        <option il-slug="Giresun" value="Güce">Güce</option>
        <option il-slug="Giresun" value="Keşap">Keşap</option>
        <option il-slug="Giresun" value="Piraziz">Piraziz</option>
        <option il-slug="Giresun" value="Şebinkarahisar">Şebinkarahisar</option>
        <option il-slug="Giresun" value="Tirebolu">Tirebolu</option>
        <option il-slug="Giresun" value="Yağlıdere">Yağlıdere</option>
        <option il-slug="Gümüşhane" value="Gümüşhane İl Merkezi">Gümüşhane İl Merkezi</option>
        <option il-slug="Gümüşhane" value="Kelkit">Kelkit</option>
        <option il-slug="Gümüşhane" value="Köse">Köse</option>
        <option il-slug="Gümüşhane" value="Kürtün">Kürtün</option>
        <option il-slug="Gümüşhane" value="Şiran">Şiran</option>
        <option il-slug="Gümüşhane" value="Torul">Torul</option>
        <option il-slug="Hakkâri" value="Hakkâri İl Merkezi">Hakkâri İl Merkezi</option>
        <option il-slug="Hakkâri" value="Çukurca">Çukurca</option>
        <option il-slug="Hakkâri" value="Derecik">Derecik</option>
        <option il-slug="Hakkâri" value="Şemdinli">Şemdinli</option>
        <option il-slug="Hakkâri" value="Yüksekova">Yüksekova</option>
        <option il-slug="Hatay" value="Altınözü">Altınözü</option>
        <option il-slug="Hatay" value="Antakya">Antakya</option>
        <option il-slug="Hatay" value="Arsuz">Arsuz</option>
        <option il-slug="Hatay" value="Belen">Belen</option>
        <option il-slug="Hatay" value="Defne">Defne</option>
        <option il-slug="Hatay" value="Dörtyol">Dörtyol</option>
        <option il-slug="Hatay" value="Erzin">Erzin</option>
        <option il-slug="Hatay" value="Hassa">Hassa</option>
        <option il-slug="Hatay" value="İskenderun">İskenderun</option>
        <option il-slug="Hatay" value="Kırıkhan">Kırıkhan</option>
        <option il-slug="Hatay" value="Kumlu">Kumlu</option>
        <option il-slug="Hatay" value="Payas">Payas</option>
        <option il-slug="Hatay" value="Reyhanlı">Reyhanlı</option>
        <option il-slug="Hatay" value="Samandağ">Samandağ</option>
        <option il-slug="Hatay" value="Yayladağı">Yayladağı</option>
        <option il-slug="Iğdır" value="Iğdır İl Merkezi">Iğdır İl Merkezi</option>
        <option il-slug="Iğdır" value="Aralık">Aralık</option>
        <option il-slug="Iğdır" value="Karakoyunlu">Karakoyunlu</option>
        <option il-slug="Iğdır" value="Tuzluca">Tuzluca</option>
        <option il-slug="Isparta" value="Isparta İl Merkezi">Isparta İl Merkezi</option>
        <option il-slug="Isparta" value="Aksu">Aksu</option>
        <option il-slug="Isparta" value="Atabey">Atabey</option>
        <option il-slug="Isparta" value="Eğirdir">Eğirdir</option>
        <option il-slug="Isparta" value="Gelendost">Gelendost</option>
        <option il-slug="Isparta" value="Gönen">Gönen</option>
        <option il-slug="Isparta" value="Keçiborlu">Keçiborlu</option>
        <option il-slug="Isparta" value="Senirkent">Senirkent</option>
        <option il-slug="Isparta" value="Sütçüler">Sütçüler</option>
        <option il-slug="Isparta" value="Şarkikaraağaç">Şarkikaraağaç</option>
        <option il-slug="Isparta" value="Uluborlu">Uluborlu</option>
        <option il-slug="Isparta" value="Yalvaç">Yalvaç</option>
        <option il-slug="Isparta" value="Yenişarbademli">Yenişarbademli</option>
        <option il-slug="İstanbul" value="Adalar">Adalar</option>
        <option il-slug="İstanbul" value="Arnavutköy">Arnavutköy</option>
        <option il-slug="İstanbul" value="Ataşehir">Ataşehir</option>
        <option il-slug="İstanbul" value="Avcılar">Avcılar</option>
        <option il-slug="İstanbul" value="Bağcılar">Bağcılar</option>
        <option il-slug="İstanbul" value="Bahçelievler">Bahçelievler</option>
        <option il-slug="İstanbul" value="Bakırköy">Bakırköy</option>
        <option il-slug="İstanbul" value="Başakşehir">Başakşehir</option>
        <option il-slug="İstanbul" value="Bayrampaşa">Bayrampaşa</option>
        <option il-slug="İstanbul" value="Beşiktaş">Beşiktaş</option>
        <option il-slug="İstanbul" value="Beykoz">Beykoz</option>
        <option il-slug="İstanbul" value="Beylikdüzü">Beylikdüzü</option>
        <option il-slug="İstanbul" value="Beyoğlu">Beyoğlu</option>
        <option il-slug="İstanbul" value="Büyükçekmece">Büyükçekmece</option>
        <option il-slug="İstanbul" value="Çatalca">Çatalca</option>
        <option il-slug="İstanbul" value="Çekmeköy">Çekmeköy</option>
        <option il-slug="İstanbul" value="Esenler">Esenler</option>
        <option il-slug="İstanbul" value="Esenyurt">Esenyurt</option>
        <option il-slug="İstanbul" value="Eyüpsultan">Eyüpsultan</option>
        <option il-slug="İstanbul" value="Fatih">Fatih</option>
        <option il-slug="İstanbul" value="Gaziosmanpaşa">Gaziosmanpaşa</option>
        <option il-slug="İstanbul" value="Güngören">Güngören</option>
        <option il-slug="İstanbul" value="Kadıköy">Kadıköy</option>
        <option il-slug="İstanbul" value="Kâğıthane">Kâğıthane</option>
        <option il-slug="İstanbul" value="Kartal">Kartal</option>
        <option il-slug="İstanbul" value="Küçükçekmece">Küçükçekmece</option>
        <option il-slug="İstanbul" value="Maltepe">Maltepe</option>
        <option il-slug="İstanbul" value="Pendik">Pendik</option>
        <option il-slug="İstanbul" value="Sancaktepe">Sancaktepe</option>
        <option il-slug="İstanbul" value="Sarıyer">Sarıyer</option>
        <option il-slug="İstanbul" value="Silivri">Silivri</option>
        <option il-slug="İstanbul" value="Sultanbeyli">Sultanbeyli</option>
        <option il-slug="İstanbul" value="Sultangazi">Sultangazi</option>
        <option il-slug="İstanbul" value="Şile">Şile</option>
        <option il-slug="İstanbul" value="Şişli">Şişli</option>
        <option il-slug="İstanbul" value="Tuzla">Tuzla</option>
        <option il-slug="İstanbul" value="Ümraniye">Ümraniye</option>
        <option il-slug="İstanbul" value="Üsküdar">Üsküdar</option>
        <option il-slug="İstanbul" value="Zeytinburnu">Zeytinburnu</option>
        <option il-slug="Zeytinburnu" value="Aliağa">Aliağa</option>
        <option il-slug="Zeytinburnu" value="Balçova">Balçova</option>
        <option il-slug="Zeytinburnu" value="Bayındır">Bayındır</option>
        <option il-slug="Zeytinburnu" value="Bayraklı">Bayraklı</option>
        <option il-slug="Zeytinburnu" value="Bergama">Bergama</option>
        <option il-slug="Zeytinburnu" value="Beydağ">Beydağ</option>
        <option il-slug="Zeytinburnu" value="Bornova">Bornova</option>
        <option il-slug="Zeytinburnu" value="Buca">Buca</option>
        <option il-slug="Zeytinburnu" value="Çeşme">Çeşme</option>
        <option il-slug="Zeytinburnu" value="Çiğli">Çiğli</option>
        <option il-slug="Zeytinburnu" value="Dikili">Dikili</option>
        <option il-slug="Zeytinburnu" value="Foça">Foça</option>
        <option il-slug="Zeytinburnu" value="Gaziemir">Gaziemir</option>
        <option il-slug="Zeytinburnu" value="Güzelbahçe">Güzelbahçe</option>
        <option il-slug="Zeytinburnu" value="Karabağlar">Karabağlar</option>
        <option il-slug="Zeytinburnu" value="Karaburun">Karaburun</option>
        <option il-slug="Zeytinburnu" value="Karşıyaka">Karşıyaka</option>
        <option il-slug="Zeytinburnu" value="Kemalpaşa">Kemalpaşa</option>
        <option il-slug="Zeytinburnu" value="Kınık">Kınık</option>
        <option il-slug="Zeytinburnu" value="Kiraz">Kiraz</option>
        <option il-slug="Zeytinburnu" value="Konak">Konak</option>
        <option il-slug="Zeytinburnu" value="Menderes">Menderes</option>
        <option il-slug="Zeytinburnu" value="Menemen">Menemen</option>
        <option il-slug="Zeytinburnu" value="Narlıdere">Narlıdere</option>
        <option il-slug="Zeytinburnu" value="Ödemiş">Ödemiş</option>
        <option il-slug="Zeytinburnu" value="Seferihisar">Seferihisar</option>
        <option il-slug="Zeytinburnu" value="Selçuk">Selçuk</option>
        <option il-slug="Zeytinburnu" value="Tire">Tire</option>
        <option il-slug="Zeytinburnu" value="Torbalı">Torbalı</option>
        <option il-slug="Zeytinburnu" value="Urla">Urla</option>
        <option il-slug="Kahramanmaraş" value="Afşin">Afşin</option>
        <option il-slug="Kahramanmaraş" value="Andırın">Andırın</option>
        <option il-slug="Kahramanmaraş" value="Çağlayancerit">Çağlayancerit</option>
        <option il-slug="Kahramanmaraş" value="Dulkadiroğlu">Dulkadiroğlu</option>
        <option il-slug="Kahramanmaraş" value="Ekinözü">Ekinözü</option>
        <option il-slug="Kahramanmaraş" value="Elbistan">Elbistan</option>
        <option il-slug="Kahramanmaraş" value="Göksun">Göksun</option>
        <option il-slug="Kahramanmaraş" value="Nurhak">Nurhak</option>
        <option il-slug="Kahramanmaraş" value="Onikişubat">Onikişubat</option>
        <option il-slug="Kahramanmaraş" value="Pazarcık">Pazarcık</option>
        <option il-slug="Kahramanmaraş" value="Türkoğlu">Türkoğlu</option>
        <option il-slug="Karabük" value="Karabük İl Merkezi">Karabük İl Merkezi</option>
        <option il-slug="Karabük" value="Eflani">Eflani</option>
        <option il-slug="Karabük" value="Eskipazar">Eskipazar</option>
        <option il-slug="Karabük" value="Ovacık">Ovacık</option>
        <option il-slug="Karabük" value="Safranbolu">Safranbolu</option>
        <option il-slug="Karabük" value="Yenice">Yenice</option>
        <option il-slug="Karaman" value="Karaman İl Merkezi">Karaman İl Merkezi</option>
        <option il-slug="Karaman" value="Ayrancı">Ayrancı</option>
        <option il-slug="Karaman" value="Başyayla">Başyayla</option>
        <option il-slug="Karaman" value="Ermenek">Ermenek</option>
        <option il-slug="Karaman" value="Kazımkarabekir">Kazımkarabekir</option>
        <option il-slug="Karaman" value="Sarıveliler">Sarıveliler</option>
        <option il-slug="Kars" value="Kars İl Merkezi">Kars İl Merkezi</option>
        <option il-slug="Kars" value="Akyaka">Akyaka</option>
        <option il-slug="Kars" value="Arpaçay">Arpaçay</option>
        <option il-slug="Kars" value="Digor">Digor</option>
        <option il-slug="Kars" value="Kağızman">Kağızman</option>
        <option il-slug="Kars" value="Sarıkamış">Sarıkamış</option>
        <option il-slug="Kars" value="Selim">Selim</option>
        <option il-slug="Kars" value="Susuz">Susuz</option>
        <option il-slug="Kastamonu" value="Kastamonu İl Merkezi">Kastamonu İl Merkezi</option>
        <option il-slug="Kastamonu" value="Abana">Abana</option>
        <option il-slug="Kastamonu" value="Ağlı">Ağlı</option>
        <option il-slug="Kastamonu" value="Araç">Araç</option>
        <option il-slug="Kastamonu" value="Azdavay">Azdavay</option>
        <option il-slug="Kastamonu" value="Bozkurt">Bozkurt</option>
        <option il-slug="Kastamonu" value="Cide">Cide</option>
        <option il-slug="Kastamonu" value="Çatalzeytin">Çatalzeytin</option>
        <option il-slug="Kastamonu" value="Daday">Daday</option>
        <option il-slug="Kastamonu" value="Devrekani">Devrekani</option>
        <option il-slug="Kastamonu" value="Doğanyurt">Doğanyurt</option>
        <option il-slug="Kastamonu" value="Hanönü">Hanönü</option>
        <option il-slug="Kastamonu" value="İhsangazi">İhsangazi</option>
        <option il-slug="Kastamonu" value="İnebolu">İnebolu</option>
        <option il-slug="Kastamonu" value="Küre">Küre</option>
        <option il-slug="Kastamonu" value="Pınarbaşı">Pınarbaşı</option>
        <option il-slug="Kastamonu" value="Seydiler">Seydiler</option>
        <option il-slug="Kastamonu" value="Şenpazar">Şenpazar</option>
        <option il-slug="Kastamonu" value="Taşköprü">Taşköprü</option>
        <option il-slug="Kastamonu" value="Tosya">Tosya</option>
        <option il-slug="Kayseri" value="Akkışla">Akkışla</option>
        <option il-slug="Kayseri" value="Bünyan">Bünyan</option>
        <option il-slug="Kayseri" value="Develi">Develi</option>
        <option il-slug="Kayseri" value="Felahiye">Felahiye</option>
        <option il-slug="Kayseri" value="Hacılar">Hacılar</option>
        <option il-slug="Kayseri" value="İncesu">İncesu</option>
        <option il-slug="Kayseri" value="Kocasinan">Kocasinan</option>
        <option il-slug="Kayseri" value="Melikgazi">Melikgazi</option>
        <option il-slug="Kayseri" value="Özvatan">Özvatan</option>
        <option il-slug="Kayseri" value="Pınarbaşı">Pınarbaşı</option>
        <option il-slug="Kayseri" value="Sarıoğlan">Sarıoğlan</option>
        <option il-slug="Kayseri" value="Sarız">Sarız</option>
        <option il-slug="Kayseri" value="Talas">Talas</option>
        <option il-slug="Kayseri" value="Tomarza">Tomarza</option>
        <option il-slug="Kayseri" value="Yahyalı">Yahyalı</option>
        <option il-slug="Kayseri" value="Yeşilhisar">Yeşilhisar</option>
        <option il-slug="Kırıkkale" value="Kırıkkale İl Merkezi">Kırıkkale İl Merkezi</option>
        <option il-slug="Kırıkkale" value="Bahşılı">Bahşılı</option>
        <option il-slug="Kırıkkale" value="Balışeyh">Balışeyh</option>
        <option il-slug="Kırıkkale" value="Çelebi">Çelebi</option>
        <option il-slug="Kırıkkale" value="Delice">Delice</option>
        <option il-slug="Kırıkkale" value="Karakeçili">Karakeçili</option>
        <option il-slug="Kırıkkale" value="Keskin">Keskin</option>
        <option il-slug="Kırıkkale" value="Sulakyurt">Sulakyurt</option>
        <option il-slug="Kırıkkale" value="Yahşihan">Yahşihan</option>
        <option il-slug="Kırklareli" value="Kırklareli İl Merkezi">Kırklareli İl Merkezi</option>
        <option il-slug="Kırklareli" value="Babaeski">Babaeski</option>
        <option il-slug="Kırklareli" value="Demirköy">Demirköy</option>
        <option il-slug="Kırklareli" value="Kofçaz">Kofçaz</option>
        <option il-slug="Kırklareli" value="Lüleburgaz">Lüleburgaz</option>
        <option il-slug="Kırklareli" value="Pehlivanköy">Pehlivanköy</option>
        <option il-slug="Kırklareli" value="Pınarhisar">Pınarhisar</option>
        <option il-slug="Kırklareli" value="Vize">Vize</option>
        <option il-slug="Kırşehir" value="Kırşehir İl Merkezi">Kırşehir İl Merkezi</option>
        <option il-slug="Kırşehir" value="Akçakent">Akçakent</option>
        <option il-slug="Kırşehir" value="Akpınar">Akpınar</option>
        <option il-slug="Kırşehir" value="Boztepe">Boztepe</option>
        <option il-slug="Kırşehir" value="Çiçekdağı">Çiçekdağı</option>
        <option il-slug="Kırşehir" value="Kaman">Kaman</option>
        <option il-slug="Kırşehir" value="Mucur">Mucur</option>
        <option il-slug="Kilis" value="Kilis İl Merkezi">Kilis İl Merkezi</option>
        <option il-slug="Kilis" value="Elbeyli">Elbeyli</option>
        <option il-slug="Kilis" value="Musabeyli">Musabeyli</option>
        <option il-slug="Kilis" value="Polateli">Polateli</option>
        <option il-slug="Kocaeli" value="Başiskele">Başiskele</option>
        <option il-slug="Kocaeli" value="Çayırova">Çayırova</option>
        <option il-slug="Kocaeli" value="Darıca">Darıca</option>
        <option il-slug="Kocaeli" value="Derince">Derince</option>
        <option il-slug="Kocaeli" value="Dilovası">Dilovası</option>
        <option il-slug="Kocaeli" value="Gebze">Gebze</option>
        <option il-slug="Kocaeli" value="Gölcük">Gölcük</option>
        <option il-slug="Kocaeli" value="İzmit">İzmit</option>
        <option il-slug="Kocaeli" value="Kandıra">Kandıra</option>
        <option il-slug="Kocaeli" value="Karamürsel">Karamürsel</option>
        <option il-slug="Kocaeli" value="Kartepe">Kartepe</option>
        <option il-slug="Kocaeli" value="Körfez">Körfez</option>
        <option il-slug="Konya" value="Ahırlı">Ahırlı</option>
        <option il-slug="Konya" value="Akören">Akören</option>
        <option il-slug="Konya" value="Akşehir">Akşehir</option>
        <option il-slug="Konya" value="Altınekin">Altınekin</option>
        <option il-slug="Konya" value="Beyşehir">Beyşehir</option>
        <option il-slug="Konya" value="Bozkır">Bozkır</option>
        <option il-slug="Konya" value="Cihanbeyli">Cihanbeyli</option>
        <option il-slug="Konya" value="Çeltik">Çeltik</option>
        <option il-slug="Konya" value="Çumra">Çumra</option>
        <option il-slug="Konya" value="Derbent">Derbent</option>
        <option il-slug="Konya" value="Derebucak">Derebucak</option>
        <option il-slug="Konya" value="Doğanhisar">Doğanhisar</option>
        <option il-slug="Konya" value="Emirgazi">Emirgazi</option>
        <option il-slug="Konya" value="Ereğli">Ereğli</option>
        <option il-slug="Konya" value="Güneysınır">Güneysınır</option>
        <option il-slug="Konya" value="Hadim">Hadim</option>
        <option il-slug="Konya" value="Halkapınar">Halkapınar</option>
        <option il-slug="Konya" value="Hüyük">Hüyük</option>
        <option il-slug="Konya" value="Ilgın">Ilgın</option>
        <option il-slug="Konya" value="Kadınhanı">Kadınhanı</option>
        <option il-slug="Konya" value="Karapınar">Karapınar</option>
        <option il-slug="Konya" value="Karatay">Karatay</option>
        <option il-slug="Konya" value="Kulu">Kulu</option>
        <option il-slug="Konya" value="Meram">Meram</option>
        <option il-slug="Konya" value="Sarayönü">Sarayönü</option>
        <option il-slug="Konya" value="Selçuklu">Selçuklu</option>
        <option il-slug="Konya" value="Seydişehir">Seydişehir</option>
        <option il-slug="Konya" value="Taşkent">Taşkent</option>
        <option il-slug="Konya" value="Tuzlukçu">Tuzlukçu</option>
        <option il-slug="Konya" value="Yalıhüyük">Yalıhüyük</option>
        <option il-slug="Konya" value="Yunak">Yunak</option>
        <option il-slug="Kütahya" value="Kütahya İl Merkezi">Kütahya İl Merkezi</option>
        <option il-slug="Kütahya" value="Altıntaş">Altıntaş</option>
        <option il-slug="Kütahya" value="Aslanapa">Aslanapa</option>
        <option il-slug="Kütahya" value="Çavdarhisar">Çavdarhisar</option>
        <option il-slug="Kütahya" value="Domaniç">Domaniç</option>
        <option il-slug="Kütahya" value="Dumlupınar">Dumlupınar</option>
        <option il-slug="Kütahya" value="Emet">Emet</option>
        <option il-slug="Kütahya" value="Gediz">Gediz</option>
        <option il-slug="Kütahya" value="Hisarcık">Hisarcık</option>
        <option il-slug="Kütahya" value="Pazarlar">Pazarlar</option>
        <option il-slug="Kütahya" value="Şaphane">Şaphane</option>
        <option il-slug="Kütahya" value="Simav">Simav</option>
        <option il-slug="Kütahya" value="Tavşanlı">Tavşanlı</option>
        <option il-slug="Malatya" value="Akçadağ">Akçadağ</option>
        <option il-slug="Malatya" value="Arapgir">Arapgir</option>
        <option il-slug="Malatya" value="Arguvan">Arguvan</option>
        <option il-slug="Malatya" value="Battalgazi">Battalgazi</option>
        <option il-slug="Malatya" value="Darende">Darende</option>
        <option il-slug="Malatya" value="Doğanşehir">Doğanşehir</option>
        <option il-slug="Malatya" value="Doğanyol">Doğanyol</option>
        <option il-slug="Malatya" value="Hekimhan">Hekimhan</option>
        <option il-slug="Malatya" value="Kale">Kale</option>
        <option il-slug="Malatya" value="Kuluncak">Kuluncak</option>
        <option il-slug="Malatya" value="Pütürge">Pütürge</option>
        <option il-slug="Malatya" value="Yazıhan">Yazıhan</option>
        <option il-slug="Malatya" value="Yeşilyurt">Yeşilyurt</option>
        <option il-slug="Manisa" value="Ahmetli">Ahmetli</option>
        <option il-slug="Manisa" value="Akhisar">Akhisar</option>
        <option il-slug="Manisa" value="Alaşehir">Alaşehir</option>
        <option il-slug="Manisa" value="Demirci">Demirci</option>
        <option il-slug="Manisa" value="Gölmarmara">Gölmarmara</option>
        <option il-slug="Manisa" value="Gördes">Gördes</option>
        <option il-slug="Manisa" value="Kırkağaç">Kırkağaç</option>
        <option il-slug="Manisa" value="Köprübaşı">Köprübaşı</option>
        <option il-slug="Manisa" value="Kula">Kula</option>
        <option il-slug="Manisa" value="Salihli">Salihli</option>
        <option il-slug="Manisa" value="Sarıgöl">Sarıgöl</option>
        <option il-slug="Manisa" value="Saruhanlı">Saruhanlı</option>
        <option il-slug="Manisa" value="Selendi">Selendi</option>
        <option il-slug="Manisa" value="Soma">Soma</option>
        <option il-slug="Manisa" value="Şehzadeler">Şehzadeler</option>
        <option il-slug="Manisa" value="Turgutlu">Turgutlu</option>
        <option il-slug="Manisa" value="Yunusemre">Yunusemre</option>
        <option il-slug="Mardin" value="Artuklu">Artuklu</option>
        <option il-slug="Mardin" value="Dargeçit">Dargeçit</option>
        <option il-slug="Mardin" value="Derik">Derik</option>
        <option il-slug="Mardin" value="Kızıltepe">Kızıltepe</option>
        <option il-slug="Mardin" value="Mazıdağı">Mazıdağı</option>
        <option il-slug="Mardin" value="Midyat">Midyat</option>
        <option il-slug="Mardin" value="Nusaybin">Nusaybin</option>
        <option il-slug="Mardin" value="Ömerli">Ömerli</option>
        <option il-slug="Mardin" value="Savur">Savur</option>
        <option il-slug="Mardin" value="Yeşilli">Yeşilli</option>
        <option il-slug="Mersin" value="Akdeniz">Akdeniz</option>
        <option il-slug="Mersin" value="Anamur">Anamur</option>
        <option il-slug="Mersin" value="Aydıncık">Aydıncık</option>
        <option il-slug="Mersin" value="Bozyazı">Bozyazı</option>
        <option il-slug="Mersin" value="Çamlıyayla">Çamlıyayla</option>
        <option il-slug="Mersin" value="Erdemli">Erdemli</option>
        <option il-slug="Mersin" value="Gülnar">Gülnar</option>
        <option il-slug="Mersin" value="Mezitli">Mezitli</option>
        <option il-slug="Mersin" value="Mut">Mut</option>
        <option il-slug="Mersin" value="Silifke">Silifke</option>
        <option il-slug="Mersin" value="Tarsus">Tarsus</option>
        <option il-slug="Mersin" value="Toroslar">Toroslar</option>
        <option il-slug="Mersin" value="Yenişehir">Yenişehir</option>
        <option il-slug="Muğla" value="Bodrum">Bodrum</option>
        <option il-slug="Muğla" value="Dalaman">Dalaman</option>
        <option il-slug="Muğla" value="Datça">Datça</option>
        <option il-slug="Muğla" value="Fethiye">Fethiye</option>
        <option il-slug="Muğla" value="Kavaklıdere">Kavaklıdere</option>
        <option il-slug="Muğla" value="Köyceğiz">Köyceğiz</option>
        <option il-slug="Muğla" value="Marmaris">Marmaris</option>
        <option il-slug="Muğla" value="Menteşe">Menteşe</option>
        <option il-slug="Muğla" value="Milas">Milas</option>
        <option il-slug="Muğla" value="Ortaca">Ortaca</option>
        <option il-slug="Muğla" value="Seydikemer">Seydikemer</option>
        <option il-slug="Muğla" value="Ula">Ula</option>
        <option il-slug="Muğla" value="Yatağan">Yatağan</option>
        <option il-slug="Muş" value="Muş İl Merkezi">Muş İl Merkezi</option>
        <option il-slug="Muş" value="Bulanık">Bulanık</option>
        <option il-slug="Muş" value="Hasköy">Hasköy</option>
        <option il-slug="Muş" value="Korkut">Korkut</option>
        <option il-slug="Muş" value="Malazgirt">Malazgirt</option>
        <option il-slug="Muş" value="Varto">Varto</option>
        <option il-slug="Nevşehir" value="Nevşehir İl Merkezi">Nevşehir İl Merkezi</option>
        <option il-slug="Nevşehir" value="Acıgöl">Acıgöl</option>
        <option il-slug="Nevşehir" value="Avanos">Avanos</option>
        <option il-slug="Nevşehir" value="Derinkuyu">Derinkuyu</option>
        <option il-slug="Nevşehir" value="Gülşehir">Gülşehir</option>
        <option il-slug="Nevşehir" value="Hacıbektaş">Hacıbektaş</option>
        <option il-slug="Nevşehir" value="Kozaklı">Kozaklı</option>
        <option il-slug="Nevşehir" value="Ürgüp">Ürgüp</option>
        <option il-slug="Niğde" value="Niğde İl Merkezi">Niğde İl Merkezi</option>
        <option il-slug="Niğde" value="Altunhisar">Altunhisar</option>
        <option il-slug="Niğde" value="Bor">Bor</option>
        <option il-slug="Niğde" value="Çamardı">Çamardı</option>
        <option il-slug="Niğde" value="Çiftlik">Çiftlik</option>
        <option il-slug="Niğde" value="Ulukışla">Ulukışla</option>
        <option il-slug="Ordu" value="Akkuş">Akkuş</option>
        <option il-slug="Ordu" value="Altınordu">Altınordu</option>
        <option il-slug="Ordu" value="Aybastı">Aybastı</option>
        <option il-slug="Ordu" value="Çamaş">Çamaş</option>
        <option il-slug="Ordu" value="Çatalpınar">Çatalpınar</option>
        <option il-slug="Ordu" value="Çaybaşı">Çaybaşı</option>
        <option il-slug="Ordu" value="Fatsa">Fatsa</option>
        <option il-slug="Ordu" value="Gölköy">Gölköy</option>
        <option il-slug="Ordu" value="Gülyalı">Gülyalı</option>
        <option il-slug="Ordu" value="Gürgentepe">Gürgentepe</option>
        <option il-slug="Ordu" value="İkizce">İkizce</option>
        <option il-slug="Ordu" value="Kabadüz">Kabadüz</option>
        <option il-slug="Ordu" value="Kabataş">Kabataş</option>
        <option il-slug="Ordu" value="Korgan">Korgan</option>
        <option il-slug="Ordu" value="Kumru">Kumru</option>
        <option il-slug="Ordu" value="Mesudiye">Mesudiye</option>
        <option il-slug="Ordu" value="Perşembe">Perşembe</option>
        <option il-slug="Ordu" value="Ulubey">Ulubey</option>
        <option il-slug="Ordu" value="Ünye">Ünye</option>
        <option il-slug="Osmaniye" value="Osmaniye İl Merkezi">Osmaniye İl Merkezi</option>
        <option il-slug="Osmaniye" value="Bahçe">Bahçe</option>
        <option il-slug="Osmaniye" value="Düziçi">Düziçi</option>
        <option il-slug="Osmaniye" value="Hasanbeyli">Hasanbeyli</option>
        <option il-slug="Osmaniye" value="Kadirli">Kadirli</option>
        <option il-slug="Osmaniye" value="Sumbas">Sumbas</option>
        <option il-slug="Osmaniye" value="Toprakkale">Toprakkale</option>
        <option il-slug="Rize" value="Rize İl Merkezi">Rize İl Merkezi</option>
        <option il-slug="Rize" value="Ardeşen">Ardeşen</option>
        <option il-slug="Rize" value="Çamlıhemşin">Çamlıhemşin</option>
        <option il-slug="Rize" value="Çayeli">Çayeli</option>
        <option il-slug="Rize" value="Derepazarı">Derepazarı</option>
        <option il-slug="Rize" value="Fındıklı">Fındıklı</option>
        <option il-slug="Rize" value="Güneysu">Güneysu</option>
        <option il-slug="Rize" value="Hemşin">Hemşin</option>
        <option il-slug="Rize" value="İkizdere">İkizdere</option>
        <option il-slug="Rize" value="İyidere">İyidere</option>
        <option il-slug="Rize" value="Kalkandere">Kalkandere</option>
        <option il-slug="Rize" value="Pazar">Pazar</option>
        <option il-slug="Sakarya" value="Adapazarı">Adapazarı</option>
        <option il-slug="Sakarya" value="Akyazı">Akyazı</option>
        <option il-slug="Sakarya" value="Arifiye">Arifiye</option>
        <option il-slug="Sakarya" value="Erenler">Erenler</option>
        <option il-slug="Sakarya" value="Ferizli">Ferizli</option>
        <option il-slug="Sakarya" value="Geyve">Geyve</option>
        <option il-slug="Sakarya" value="Hendek">Hendek</option>
        <option il-slug="Sakarya" value="Karapürçek">Karapürçek</option>
        <option il-slug="Sakarya" value="Karasu">Karasu</option>
        <option il-slug="Sakarya" value="Kaynarca">Kaynarca</option>
        <option il-slug="Sakarya" value="Kocaali">Kocaali</option>
        <option il-slug="Sakarya" value="Pamukova">Pamukova</option>
        <option il-slug="Sakarya" value="Sapanca">Sapanca</option>
        <option il-slug="Sakarya" value="Serdivan">Serdivan</option>
        <option il-slug="Sakarya" value="Söğütlü">Söğütlü</option>
        <option il-slug="Sakarya" value="Taraklı">Taraklı</option>
        <option il-slug="Samsun" value="19Mayıs">19Mayıs</option>
        <option il-slug="Samsun" value="Alaçam">Alaçam</option>
        <option il-slug="Samsun" value="Asarcık">Asarcık</option>
        <option il-slug="Samsun" value="Atakum">Atakum</option>
        <option il-slug="Samsun" value="Ayvacık">Ayvacık</option>
        <option il-slug="Samsun" value="Bafra">Bafra</option>
        <option il-slug="Samsun" value="Canik">Canik</option>
        <option il-slug="Samsun" value="Çarşamba">Çarşamba</option>
        <option il-slug="Samsun" value="Havza">Havza</option>
        <option il-slug="Samsun" value="İlkadım">İlkadım</option>
        <option il-slug="Samsun" value="Kavak">Kavak</option>
        <option il-slug="Samsun" value="Ladik">Ladik</option>
        <option il-slug="Samsun" value="Salıpazarı">Salıpazarı</option>
        <option il-slug="Samsun" value="Tekkeköy">Tekkeköy</option>
        <option il-slug="Samsun" value="Terme">Terme</option>
        <option il-slug="Samsun" value="Vezirköprü">Vezirköprü</option>
        <option il-slug="Samsun" value="Yakakent">Yakakent</option>
        <option il-slug="Siirt" value="Siirt İl Merkezi">Siirt İl Merkezi</option>
        <option il-slug="Siirt" value="Baykan">Baykan</option>
        <option il-slug="Siirt" value="Eruh">Eruh</option>
        <option il-slug="Siirt" value="Kurtalan">Kurtalan</option>
        <option il-slug="Siirt" value="Pervari">Pervari</option>
        <option il-slug="Siirt" value="Şirvan">Şirvan</option>
        <option il-slug="Siirt" value="Tillo">Tillo</option>
        <option il-slug="Sinop" value="Sinop İl Merkezi">Sinop İl Merkezi</option>
        <option il-slug="Sinop" value="Ayancık">Ayancık</option>
        <option il-slug="Sinop" value="Boyabat">Boyabat</option>
        <option il-slug="Sinop" value="Dikmen">Dikmen</option>
        <option il-slug="Sinop" value="Durağan">Durağan</option>
        <option il-slug="Sinop" value="Erfelek">Erfelek</option>
        <option il-slug="Sinop" value="Gerze">Gerze</option>
        <option il-slug="Sinop" value="Saraydüzü">Saraydüzü</option>
        <option il-slug="Sinop" value="Türkeli">Türkeli</option>
        <option il-slug="Sivas" value="Sivas İl Merkezi">Sivas İl Merkezi</option>
        <option il-slug="Sivas" value="Akıncılar">Akıncılar</option>
        <option il-slug="Sivas" value="Altınyayla">Altınyayla</option>
        <option il-slug="Sivas" value="Divriği">Divriği</option>
        <option il-slug="Sivas" value="Doğanşar">Doğanşar</option>
        <option il-slug="Sivas" value="Gemerek">Gemerek</option>
        <option il-slug="Sivas" value="Gölova">Gölova</option>
        <option il-slug="Sivas" value="Gürün">Gürün</option>
        <option il-slug="Sivas" value="Hafik">Hafik</option>
        <option il-slug="Sivas" value="İmranlı">İmranlı</option>
        <option il-slug="Sivas" value="Kangal">Kangal</option>
        <option il-slug="Sivas" value="Koyulhisar">Koyulhisar</option>
        <option il-slug="Sivas" value="Suşehri">Suşehri</option>
        <option il-slug="Sivas" value="Şarkışla">Şarkışla</option>
        <option il-slug="Sivas" value="Ulaş">Ulaş</option>
        <option il-slug="Sivas" value="Yıldızeli">Yıldızeli</option>
        <option il-slug="Sivas" value="Zara">Zara</option>
        <option il-slug="Şanlıurfa" value="Akçakale">Akçakale</option>
        <option il-slug="Şanlıurfa" value="Birecik">Birecik</option>
        <option il-slug="Şanlıurfa" value="Bozova">Bozova</option>
        <option il-slug="Şanlıurfa" value="Ceylanpınar">Ceylanpınar</option>
        <option il-slug="Şanlıurfa" value="Eyyübiye">Eyyübiye</option>
        <option il-slug="Şanlıurfa" value="Halfeti">Halfeti</option>
        <option il-slug="Şanlıurfa" value="Haliliye">Haliliye</option>
        <option il-slug="Şanlıurfa" value="Harran">Harran</option>
        <option il-slug="Şanlıurfa" value="Hilvan">Hilvan</option>
        <option il-slug="Şanlıurfa" value="Karaköprü">Karaköprü</option>
        <option il-slug="Şanlıurfa" value="Siverek">Siverek</option>
        <option il-slug="Şanlıurfa" value="Suruç">Suruç</option>
        <option il-slug="Şanlıurfa" value="Viranşehir">Viranşehir</option>
        <option il-slug="Şırnak" value="Şırnak İl Merkezi">Şırnak İl Merkezi</option>
        <option il-slug="Şırnak" value="Beytüşşebap">Beytüşşebap</option>
        <option il-slug="Şırnak" value="Cizre">Cizre</option>
        <option il-slug="Şırnak" value="Güçlükonak">Güçlükonak</option>
        <option il-slug="Şırnak" value="İdil">İdil</option>
        <option il-slug="Şırnak" value="Silopi">Silopi</option>
        <option il-slug="Şırnak" value="Uludere">Uludere</option>
        <option il-slug="Tekirdağ" value="Çerkezköy">Çerkezköy</option>
        <option il-slug="Tekirdağ" value="Çorlu">Çorlu</option>
        <option il-slug="Tekirdağ" value="Ergene">Ergene</option>
        <option il-slug="Tekirdağ" value="Hayrabolu">Hayrabolu</option>
        <option il-slug="Tekirdağ" value="Kapaklı">Kapaklı</option>
        <option il-slug="Tekirdağ" value="Malkara">Malkara</option>
        <option il-slug="Tekirdağ" value="Marmaraereğlisi">Marmaraereğlisi</option>
        <option il-slug="Tekirdağ" value="Muratlı">Muratlı</option>
        <option il-slug="Tekirdağ" value="Saray">Saray</option>
        <option il-slug="Tekirdağ" value="Süleymanpaşa">Süleymanpaşa</option>
        <option il-slug="Tekirdağ" value="Şarköy">Şarköy</option>
        <option il-slug="Tokat" value="Tokat İl Merkezi">Tokat İl Merkezi</option>
        <option il-slug="Tokat" value="Almus">Almus</option>
        <option il-slug="Tokat" value="Artova">Artova</option>
        <option il-slug="Tokat" value="Başçiftlik">Başçiftlik</option>
        <option il-slug="Tokat" value="Erbaa">Erbaa</option>
        <option il-slug="Tokat" value="Niksar">Niksar</option>
        <option il-slug="Tokat" value="Pazar">Pazar</option>
        <option il-slug="Tokat" value="Reşadiye">Reşadiye</option>
        <option il-slug="Tokat" value="Sulusaray">Sulusaray</option>
        <option il-slug="Tokat" value="Turhal">Turhal</option>
        <option il-slug="Tokat" value="Yeşilyurt">Yeşilyurt</option>
        <option il-slug="Tokat" value="Zile">Zile</option>
        <option il-slug="Trabzon" value="Akçaabat">Akçaabat</option>
        <option il-slug="Trabzon" value="Araklı">Araklı</option>
        <option il-slug="Trabzon" value="Arsin">Arsin</option>
        <option il-slug="Trabzon" value="Beşikdüzü">Beşikdüzü</option>
        <option il-slug="Trabzon" value="Çarşıbaşı">Çarşıbaşı</option>
        <option il-slug="Trabzon" value="Çaykara">Çaykara</option>
        <option il-slug="Trabzon" value="Dernekpazarı">Dernekpazarı</option>
        <option il-slug="Trabzon" value="Düzköy">Düzköy</option>
        <option il-slug="Trabzon" value="Hayrat">Hayrat</option>
        <option il-slug="Trabzon" value="Köprübaşı">Köprübaşı</option>
        <option il-slug="Trabzon" value="Maçka">Maçka</option>
        <option il-slug="Trabzon" value="Of">Of</option>
        <option il-slug="Trabzon" value="Ortahisar">Ortahisar</option>
        <option il-slug="Trabzon" value="Sürmene">Sürmene</option>
        <option il-slug="Trabzon" value="Şalpazarı">Şalpazarı</option>
        <option il-slug="Trabzon" value="Tonya">Tonya</option>
        <option il-slug="Trabzon" value="Vakfıkebir">Vakfıkebir</option>
        <option il-slug="Trabzon" value="Yomra">Yomra</option>
        <option il-slug="Tunceli" value="Tunceli İl Merkezi">Tunceli İl Merkezi</option>
        <option il-slug="Tunceli" value="Çemişgezek">Çemişgezek</option>
        <option il-slug="Tunceli" value="Hozat">Hozat</option>
        <option il-slug="Tunceli" value="Mazgirt">Mazgirt</option>
        <option il-slug="Tunceli" value="Nazımiye">Nazımiye</option>
        <option il-slug="Tunceli" value="Ovacık">Ovacık</option>
        <option il-slug="Tunceli" value="Pertek">Pertek</option>
        <option il-slug="Tunceli" value="Pülümür">Pülümür</option>
        <option il-slug="Uşak" value="Uşak İl Merkezi">Uşak İl Merkezi</option>
        <option il-slug="Uşak" value="Banaz">Banaz</option>
        <option il-slug="Uşak" value="Eşme">Eşme</option>
        <option il-slug="Uşak" value="Karahallı">Karahallı</option>
        <option il-slug="Uşak" value="Sivaslı">Sivaslı</option>
        <option il-slug="Uşak" value="Ulubey">Ulubey</option>
        <option il-slug="Van" value="Bahçesaray">Bahçesaray</option>
        <option il-slug="Van" value="Başkale">Başkale</option>
        <option il-slug="Van" value="Çaldıran">Çaldıran</option>
        <option il-slug="Van" value="Çatak">Çatak</option>
        <option il-slug="Van" value="Edremit">Edremit</option>
        <option il-slug="Van" value="Erciş">Erciş</option>
        <option il-slug="Van" value="Gevaş">Gevaş</option>
        <option il-slug="Van" value="Gürpınar">Gürpınar</option>
        <option il-slug="Van" value="İpekyolu">İpekyolu</option>
        <option il-slug="Van" value="Muradiye">Muradiye</option>
        <option il-slug="Van" value="Özalp">Özalp</option>
        <option il-slug="Van" value="Saray">Saray</option>
        <option il-slug="Van" value="Tuşba">Tuşba</option>
        <option il-slug="Yalova" value="Yalova İl Merkezi">Yalova İl Merkezi</option>
        <option il-slug="Yalova" value="Altınova">Altınova</option>
        <option il-slug="Yalova" value="Armutlu">Armutlu</option>
        <option il-slug="Yalova" value="Çınarcık">Çınarcık</option>
        <option il-slug="Yalova" value="Çiftlikköy">Çiftlikköy</option>
        <option il-slug="Yalova" value="Termal">Termal</option>
        <option il-slug="Yozgat" value="Yozgat İl Merkezi">Yozgat İl Merkezi</option>
        <option il-slug="Yozgat" value="Akdağmadeni">Akdağmadeni</option>
        <option il-slug="Yozgat" value="Aydıncık">Aydıncık</option>
        <option il-slug="Yozgat" value="Boğazlıyan">Boğazlıyan</option>
        <option il-slug="Yozgat" value="Çandır">Çandır</option>
        <option il-slug="Yozgat" value="Çayıralan">Çayıralan</option>
        <option il-slug="Yozgat" value="Çekerek">Çekerek</option>
        <option il-slug="Yozgat" value="Kadışehri">Kadışehri</option>
        <option il-slug="Yozgat" value="Saraykent">Saraykent</option>
        <option il-slug="Yozgat" value="Sarıkaya">Sarıkaya</option>
        <option il-slug="Yozgat" value="Sorgun">Sorgun</option>
        <option il-slug="Yozgat" value="Şefaatli">Şefaatli</option>
        <option il-slug="Yozgat" value="Yenifakılı">Yenifakılı</option>
        <option il-slug="Yozgat" value="Yerköy">Yerköy</option>
        <option il-slug="Zonguldak" value="Zonguldak İl Merkezi">Zonguldak İl Merkezi</option>
        <option il-slug="Zonguldak" value="Alaplı">Alaplı</option>
        <option il-slug="Zonguldak" value="Çaycuma">Çaycuma</option>
        <option il-slug="Zonguldak" value="Devrek">Devrek</option>
        <option il-slug="Zonguldak" value="Gökçebey">Gökçebey</option>
        <option il-slug="Zonguldak" value="Karadeniz">Karadeniz</option> Ereğli
        <option il-slug="Zonguldak" value="Kilimli">Kilimli</option>
        <option il-slug="Zonguldak" value="Kozlu">Kozlu</option><?php
    }
?>